### ISSUE TITLE
No code yet?

### ISSUE THREAD

**Issue by douglascrp** [ITDSystems/data-spider#1]
Hey @aviriel 

Are you still going to share the project's code?
I've just watched your presentation here https://www.youtube.com/watch?v=t50IVAxpD3E&feature=youtu.be&t=1061 and I'd like to take a look at the project.

It seems really cool.

**Comment by aviriel** [comment]
Hi Douglas,

We are really sorry, but we still didn't share the code. :( If you have a similar project and need this code, contact me privately, we can share it. The problem is that we still can not find a time to make review the code, delete customer specific code, translate custom Share pages to Russian and then publish the extension.
